name: Archive

on: [push]

jobs:
  build:    
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [10.x]

    steps:      
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        working-directory: ./FightTimeLine/ClientApp
        run: |        
          npm install      
          npm run ng-high-memory -- --prod
        env:
          CI: true
      - name: remove assets
        working-directory: ./FightTimeLine/ClientApp/dist
        run: |
          rm -r assets
      - name: send to ftp
        if: github.ref == 'refs/heads/master'                
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          ftp-server: ftp://ftp-eu.site4now.net/shb/ClientApp/dist
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./FightTimeLine/ClientApp/dist
          git-ftp-args: --all        
